### ISSUE TITLE
install from pyPi failing

### ISSUE THREAD

**Issue by bryonjacob** [transitland/mapzen-geohash#5]
I just tried to install mzgeohash from pypi, and I got the following

```
$ pip install mzgeohash
Collecting mzgeohash
  Using cached https://files.pythonhosted.org/packages/77/54/48e792a0fa9ff39550feed21c2c4e4bf583b2862a96e879bd1e3969c1e09/mzgeohash-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3y/xcklh6_96zz_f9d4bmk86p0h0000gn/T/pip-install-zus2aeos/mzgeohash/setup.py", line 3, in <module>
        import mzgeohash
      File "/private/var/folders/3y/xcklh6_96zz_f9d4bmk86p0h0000gn/T/pip-install-zus2aeos/mzgeohash/mzgeohash/__init__.py", line 1, in <module>
        from geohash import encode, decode, adjacent, neighbors, neighborsfit
    ModuleNotFoundError: No module named 'geohash'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3y/xcklh6_96zz_f9d4bmk86p0h0000gn/T/pip-install-zus2aeos/mzgeohash/
```

my version info:
```
$ python --version
Python 3.6.5
$ pip --version
pip 10.0.1 from /Users/bryon/.virtualenvs/adhoc/lib/python3.6/site-packages/pip (python 3.6)
```

Checking it out locally and installing had the same error - but with a one-line change in the `__init__.py` file fixed it  - I made the change in a fork here:

https://github.com/bryonjacob/mapzen-geohash/commit/ce027d55d8afeca4a85bf2d6ee95c69a3253306e

LMK if I should submit a pull request - thanks!

**Comment by shahbazahmed1269** [comment]
I am facing the same issue. Below is the version info:
```
$ python --version
Python 3.4.3
$ pip --version
pip 18.1
```
This has to be fixed, but it seems this library is not being maintained of late.

**Comment by agile** [comment]
@jason-h-simplifi has a fix for this https://github.com/jason-h-simplifi/mapzen-geohash and repackaged as https://pypi.python.org/pypi/mz2geohash

**Comment by vevetron** [comment]
Still an issue:

```MacBook-Pro:transit-amenity-atlas$ pip install mzgeohash
Collecting mzgeohash
  Downloading mzgeohash-1.0.0.tar.gz (3.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/.pyenv/versions/3.11.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/.pyenv/versions/3.11.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/.pyenv/versions/3.11.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/cd/f7f0k_9x33db5kznz2z3nkb40000gn/T/pip-build-env-p18hwzy2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/cd/f7f0k_9x33db5kznz2z3nkb40000gn/T/pip-build-env-p18hwzy2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/cd/f7f0k_9x33db5kznz2z3nkb40000gn/T/pip-build-env-p18hwzy2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/cd/f7f0k_9x33db5kznz2z3nkb40000gn/T/pip-build-env-p18hwzy2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/private/var/folders/cd/f7f0k_9x33db5kznz2z3nkb40000gn/T/pip-install-1oegmgel/mzgeohash_63d4c9b1c3674feb82a888988b888bec/mzgeohash/__init__.py", line 1, in <module>
          from geohash import encode, decode, adjacent, neighbors, neighborsfit
      ModuleNotFoundError: No module named 'geohash'
      [end of output]
```

**Comment by irees** [comment]
@vevetron I'm surprised to see activity on this old repo! I'll try to update the package if I get a chance, but this is 10 year old code. You may want to just look at `mzgeohash/geohash.py` and copy out the code that you need - it has no external dependencies, and the code itself should still work fine even if python packaging scripts has become out of date.

**Comment by irees** [comment]
@vevetron My python packaging is very rusty, but while I was waiting on a build in another project I was able to update this repo and push a new release to pypi. `python3 -m pip install mzgeohash` should work now, because Cal-ITP asked :) https://pypi.org/project/mzgeohash/

**Comment by vevetron** [comment]
Thank you @irees !
